name: Helm Deployer
description: Helm deployer with route verification or penetration testing
branding:
  icon: package
  color: blue

inputs:
  ### Required
  chart:
    description: Chart director (e.g. frontend/openshift.deploy.yml)
    required: true
  namespace:
    description: OpenShift or Kubernetes namespace (e.g. abc123-dev)
    required: true
  server:
    description: OpenShift or Kubernetes server (e.g. https://api.silver.devops.gov.bc.ca:6443)
    required: true
  token:
    description: OpenShift or Kubernetes access token
    required: true
  release:
    description: Helm release
    required: true

  ### Typical / recommended
  directory:
    descrption: Directory with Helm charts
    default: "."
  parameters:
    description: Template parameters/variables to pass (e.g. --set ZONE=...)
    default: ""
  triggers:
    description: Omit to always build, otherwise trigger by path; e.g. ('./backend/', './frontend/)

  ### Usually a bad idea / not recommended
  diff_branch:
    default: ${{ github.event.repository.default_branch }}
    description: Branch to diff against
  repository:
    default: ${{ github.repository }}
    description: Optionally, specify a different repo to clone
  branch:
    default: ''
    description: Optionally, specify a different branch to clone

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}

    # Process variables and inputs
    - id: vars
      shell: bash
      run: |
        # Expand for inputs and variables

        # Bug mitigation - OpenShift/Kubernetes hates images with capitals in org/repo names
        REPO=${{ inputs.repository }}
        if [[ $REPO != ${REPO,,} ]]; then
          echo -e "An OpenShift bug prevents capital letters in repo names.\n"
          echo -e "Please handle that using the `repository` parameter.\n"
          exit 1
        fi

        # Triggers
        TRIGGERS=${{ inputs.triggers }}
        if [ -z "${TRIGGERS}" ]; then
          echo "Triggers omitted, deployment required"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "Processing triggers"
          git fetch origin "${{ inputs.diff_branch }}"
          while read -r check; do
            for t in "${TRIGGERS[@]}"; do
              if [[ "${check}" =~ "${t}" ]]; then
                  echo -e "Triggered: ${t}\n --> ${check}"
                  echo "triggered=true" >> $GITHUB_OUTPUT
                  exit 0
              fi
            done
          done < <(git diff origin/"${{ inputs.diff_branch }}" --name-only)
        fi
        echo "Triggers not matched, deployment skipped"

    - name: Deploy
      if: steps.vars.outputs.triggered
      shell: bash
      run: |
        # Expand for deployment steps

        # Allow pipefail, since we could be catching oc create errors
        set +o pipefail

        # Login to OpenShift (NOTE: project command is a safeguard)
        oc login --token=${{ inputs.token }} --server=${{ inputs.server }}
        oc project ${{ inputs.namespace }}

        helm upgrade ${{ inputs.release }} ${{ inputs.directory }} -i --atomic --debug ${{ inputs.parameters }} \
            | sed '/^kind: Secret/,/^[^ ]/{//!d}' | sed '/^kind: Secret/ s/$/ \n  <REDACTED>/'

    # Action repo needs to be present for cleanup/tests
    - name: Checkout to make sure action.yml is present (tests)/
      if: ${{ github.repository }} != ${{ inputs.repository }}
      uses: actions/checkout@v3
