{{- if .Values.configmap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "templates.fullname" . }}
  labels:
    {{- include "templates.labels" . | nindent 4 }}
data:
  {{- include "templates.configmap" . | nindent 2 }}
{{- end }}
