---
{{- if .Values.imagestream.enabled -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "templates.fullname" . }}
  labels:
    {{- include "templates.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
{{- range .Values.imagestream.streams }}
    - name: {{ .name }}:{{ .tag }}
      from:
        kind: DockerImage
        name: {{ .repository }}:{{ .tag }}
      referencePolicy:
        type: Local
{{- end }}

# imagestream:
#   enabled: true
  # streams:
  #  - name: my-imagestream-1
  #    repository: my-docker-repo-1
  #    tag: latest
  #  - name: my-imagestream-2
  #    repository: my-docker-repo-2
  #    tag: latest