---
{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "component.fullname" . }}
  labels:
    {{- include "component.labels" . | nindent 4 }}
data:
    {{- range  .Values.configmap.data }}
    {{ .name }}: {{ .value }}
    {{- end }}

{{- end }}
