{{- if .Values.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "component.fullname" . }}
  labels:
    {{- include "component.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "component.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "component.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "component.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ include "component.fullname" . }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ include "component.fullname" . }}
          {{- if .Values.vault.enabled}}
          args:
            - 'sh'
            - '-c'
            - '{{- range $k := .Values.vault.secrets }}source /vault/secrets/{{$k}} && {{- end}}{{ .Values.vault.entrypoint }}'
          {{- end}}
          env:
          {{- range $k,$v := fromYaml (.Values.configmap.env) }}
            - name: {{$k}}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "component.fullname" $ }}
                  key: {{$k}}
          {{- end }}
          {{- range $k,$v := fromYaml (.Values.secret.data) }}
            - name: {{$k}}
              valueFrom:
                secretKeyRef:
                  name: {{ include "component.fullname" $ }}
                  key: {{$k}}
          {{- end }}
          {{- if .Values.container.ports}}
          {{- with .Values.container.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- else }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- end }}
          {{- if .Values.container.resources}}
          {{- with .Values.container.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- else }}
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 20m
              memory: 50Mi
          {{- end }}
          {{- if .Values.container.readinessProbe}}
          {{- with .Values.container.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- else }}
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
          {{- end }}
          {{- with .Values.container.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.container.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
