{{- if and .Values.secret  .Values.secret.data }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.secret.persistent }} # mainly for dev, test, prod, for sandbox it does not need to persist as helm uninstall needs to clean the namespace.
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    {{- include "component.labels" . | nindent 4 }}
  name: {{ include "component.fullname" . }}
data:
  {{- range .Values.secret.data }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
{{- end }}
