name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  repo_builds: bcgov/quickstart-openshift@

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v3
      - name: Deploys
        uses: ./
        with:
          directory: charts/init
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          parameters:
            --set ZONE=${{ github.event.number }} --set NAME=${{ github.event.repository.name }}
            --set repo=quickstart-openshift 
          release: ${{ github.event.repository.name }}-${{ github.event.number }}
          repository: bcgov/quickstart-openshift@feat/subcharts
