name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  repo_builds: bcgov/quickstart-openshift@

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v3
      - name: Deploys
        uses: ./
        with:
          directory: charts/init
          namespace: ${{ vars.OC_NAMESPACE }}
          server: ${{ vars.OC_SERVER }}
          token: ${{ secrets.OC_TOKEN }}
          parameters:
            --set zone=${{ github.event.number }} --set repo=quickstart-openshift
          repository: bcgov/quickstart-openshift
          branch: feat/subcharts
          release: ${{ github.event.repository.name }}-${{ github.event.number }}-init

  database:
    name: Database
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v3
      - name: Deploys
        uses: ./
        with:
          directory: charts/database
          namespace: ${{ vars.OC_NAMESPACE }}
          server: ${{ vars.OC_SERVER }}
          token: ${{ secrets.OC_TOKEN }}
          parameters:
            --set zone=${{ github.event.number }} --set repo=quickstart-openshift --set org=bcgov
          repository: bcgov/quickstart-openshift
          branch: feat/subcharts
          release: ${{ github.event.repository.name }}-${{ github.event.number }}-database
